/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminPart;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author jaina
 */
public class IssueBooks extends javax.swing.JFrame {
    String isbn, state, studRollNo, bookName, category, studName, gender, department, studentId, adminId;
    int rollNo;
    String errorLabel="";
    boolean flag=false;
    boolean status;
    /**
     * Creates new form IssueBooks
     */
    public IssueBooks(String Id) {
        initComponents();
        this.adminId = Id;
        setVisible(true);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel10.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
    }

    private IssueBooks() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 8, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Colonna MT", 3, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Library Management System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Issue Books!!!");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 660, 100));

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 5, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Please Enter Book Details Here:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 18, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("( Example is given )");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 25, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ISBN No.:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 133, -1));

        jTextField1.setBackground(new java.awt.Color(51, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("1234567890123");
        jTextField1.setToolTipText("Enter ISBN No. Of The Book.");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 85, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Book Name: ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 90, 150, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(51, 255, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Java World");
        jTextField2.setToolTipText("You can't edit this field.");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 85, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Category:");
        jLabel7.setToolTipText("");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(51, 255, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("John Doe");
        jTextField3.setToolTipText("You can't edit this field.");
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 135, 140, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Book Status:");
        jLabel8.setToolTipText("");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 140, 150, -1));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(51, 255, 255));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(102, 102, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Unavailable");
        jTextField4.setToolTipText("You can't edit this field.");
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 135, 140, 30));

        jTextField5.setBackground(new java.awt.Color(51, 255, 255));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(102, 102, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("120");
        jTextField5.setToolTipText("");
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 235, 140, 30));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(51, 255, 255));
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(102, 102, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("John Doe");
        jTextField6.setToolTipText("You can't edit this field.");
        jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 235, 140, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Roll No.:");
        jLabel9.setToolTipText("");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Name:");
        jLabel10.setToolTipText("");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 240, 150, -1));

        jLabel11.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 255));
        jLabel11.setText("Please Enter Student Details Here:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 175, -1, -1));

        jLabel12.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jLabel12.setText("( Example is given )");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 182, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Gender:");
        jLabel13.setToolTipText("");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 130, -1));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(51, 255, 255));
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(102, 102, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("Others");
        jTextField7.setToolTipText("You can't edit this field.");
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 285, 140, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Department:");
        jLabel14.setToolTipText("");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 290, 150, -1));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(51, 255, 255));
        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(102, 102, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("IT");
        jTextField8.setToolTipText("You can't edit this field.");
        jTextField8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 285, 140, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 640, 330));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3_IssueBook.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 120, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/0_PreviousButton.jpg"))); // NOI18N
        jButton2.setToolTipText("To Go To Previous Page.");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 75, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        errorLabel="";
        String l1 = validateTextField1();
        String l2 = validateTextField5();
        String label = l1+l2;
        if(flag)
        {
            JOptionPane.showMessageDialog(this, label,"ERRORS",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            rollNo = Integer.parseInt(studRollNo);
            Connection con=null;
            PreparedStatement pst=null;
            try{
                String url = "jdbc:mysql://localhost:3306/library";
                String MySQLname = "root";
                String password = "";
                //Class.forName("com.mysql.jdbc.Driver");
                con=(Connection) DriverManager.getConnection(url,MySQLname,password);
                if(con == null)
                {
                    JOptionPane.showMessageDialog(this, "Error in Connecting To Database!!");
                }
                else
                {
                    System.out.println("Connected to database\n"+con.toString()+"\n");
                    String sql="SELECT * FROM book WHERE ISBNNo = "+isbn; //select all books 
                    pst = (PreparedStatement)con.prepareStatement(sql);
                    ResultSet rs=pst.executeQuery(sql); //view data in table format
                    if(rs.next())
                    {
                        bookName = rs.getString("BookName");
                        category = rs.getString("Category");
                        status = rs.getBoolean("Status");
                        if(status == true)
                        {
                            state = "Available";
                        }
                        else
                        {
                            state = "Unavailable";
                        }
                        jTextField2.setText(bookName);
                        jTextField3.setText(category);
                        jTextField4.setText(state);
                    }
                    pst.close();
                    rs.close();
                    sql="SELECT * FROM student where RollNo = "+rollNo; //select all books 
                    pst = (PreparedStatement)con.prepareStatement(sql);
                    rs=pst.executeQuery(sql); //view data in table format
                    if(rs.next())
                    {
                        studName = rs.getString("Name");
                        studentId = rs.getString("UserName");
                        gender = rs.getString("Gender");
                        department = rs.getString("Department");
                        jTextField6.setText(studName);
                        jTextField7.setText(gender);
                        jTextField8.setText(department);
                    }
                    pst.close();
                    rs.close();
                    JOptionPane.showMessageDialog(this, "Please Verify Book Details and Student Details!!");
                    jLabel6.setVisible(true);
                    jLabel7.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel10.setVisible(true);
                    jLabel13.setVisible(true);
                    jLabel14.setVisible(true);
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jTextField6.setVisible(true);
                    jTextField7.setVisible(true);
                    jTextField8.setVisible(true);
                    if(status)    
                    {
                        int option = JOptionPane.showConfirmDialog(this, "Are you SURE you want to Issue this book?", "Confirmation", JOptionPane.YES_NO_OPTION);
                        if(option==0)
                        {
                            String adminId2;
                            boolean validChecker;
                            do{
                                adminId2 =  JOptionPane.showInputDialog("Admin Id.");
                                JOptionPane.showMessageDialog( this, adminId2 );
                                validChecker = adminId.equals(adminId2);
                                if(validChecker==false)
                                {
                                    JOptionPane.showMessageDialog( this, "You have not entered Valid AdminId !!!" );
                                }
                            }while(validChecker==false);
                            Timestamp issueId = new Timestamp(System.currentTimeMillis());
                            Timestamp dueTimeStamp = new Timestamp(System.currentTimeMillis());
                            Calendar cal = Calendar.getInstance();
                            cal.setTime(dueTimeStamp);
                            cal.add(Calendar.DAY_OF_WEEK, 7);
                             //dueTimeStamp.setTime(cal.getTime().getTime()); // or
                            dueTimeStamp = new Timestamp(cal.getTime().getTime());
                            //String issueId = issueIds.toString();
                            sql = "INSERT INTO issuedBooks (IssueId, BookISBNNo, AdminId, StudentId, DueTimeStamp)"+" VALUES (?, ?, ?, ?, ?)";
                            pst=con.prepareStatement(sql);
                            pst.setTimestamp(1, issueId);
                            pst.setString(2,isbn);
                            pst.setString(3,adminId);
                            pst.setString(4,studentId);
                            pst.setTimestamp(5,dueTimeStamp);
                            //pst.setBoolean(7,bookStatus);
                            int r=pst.executeUpdate();
                            //            ResultSet rs=pst.executeQuery(sql); //view data in table format
                            pst.close();
                            con.close();
                            //            rs.close();
                            if(r>0)
                            {JOptionPane.showMessageDialog(this, "Book "+bookName+" of ISBN No.:"+isbn+" is Issued Successfully to student with Roll No.: "+rollNo+" !!","Message",JOptionPane.INFORMATION_MESSAGE);}
                            jTextField1.setText(null);
                            jTextField5.setText(null);
                            jLabel6.setVisible(false);
                            jLabel7.setVisible(false);
                            jLabel8.setVisible(false);
                            jLabel10.setVisible(false);
                            jLabel13.setVisible(false);
                            jLabel14.setVisible(false);
                            jTextField2.setVisible(false);
                            jTextField3.setVisible(false);
                            jTextField4.setVisible(false);
                            jTextField6.setVisible(false);
                            jTextField7.setVisible(false);
                            jTextField8.setVisible(false);
                        }
                        else
                        {
                            jLabel6.setVisible(false);
                            jLabel7.setVisible(false);
                            jLabel8.setVisible(false);
                            jLabel10.setVisible(false);
                            jLabel13.setVisible(false);
                            jLabel14.setVisible(false);
                            jTextField1.setText(null);
                            jTextField5.setText(null);
                            jTextField2.setVisible(false);
                            jTextField3.setVisible(false);
                            jTextField4.setVisible(false);
                            jTextField6.setVisible(false);
                            jTextField7.setVisible(false);
                            jTextField8.setVisible(false);
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Book "+bookName+" of ISBN No.:"+isbn+" cannot be Issued, as it is NOT Available in the library!!","Message",JOptionPane.INFORMATION_MESSAGE);
                        jTextField1.setText(null);
                        jTextField5.setText(null);
                        jTextField2.setVisible(false);
                        jTextField3.setVisible(false);
                        jTextField4.setVisible(false);
                        jTextField6.setVisible(false);
                        jTextField7.setVisible(false);
                        jTextField8.setVisible(false);
                    }
                }
                }catch (Exception e1) {
                    // TODO Auto-generated catch block
                    JOptionPane.showMessageDialog(null, e1);
                }
        //jLabel12.setText(label);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public String validateTextField1()
    {
        errorLabel="";
        flag=false;
        isbn = jTextField1.getText();
        if(isbn.equals("") || isbn.length()!=13)
        {
            errorLabel = errorLabel + " Enter ISBN No. of 13 digit.";
            jTextField1.setText(null);
            flag=true;
        }
        
        if(isbn.length()==13)
        {
            char arr[] = isbn.toCharArray();
            for(int i=0; i<13; i++)
            {
                if(arr[i]<48 || arr[i]>57)
                {
                    errorLabel = errorLabel + " ISBN No. Should be Digits Only.";
                    jTextField1.setText(null);
                    flag=true;
                    break;
                }
            }
        }
        return errorLabel;
    }
    
    public String validateTextField5()
    {
        errorLabel="";
        studRollNo = jTextField5.getText();
        if(studRollNo.equals(""))
        {
            errorLabel = errorLabel + "\n Enter Roll No.";
            jTextField5.setText(null);
            flag=true;
        }
        else
        {
            char arr[] = studRollNo.toCharArray();
            for(int i=0; i<studRollNo.length(); i++)
            {
                if(arr[i]<48 || arr[i]>57)
                {
                    errorLabel = errorLabel + " Roll No. Should be digits only.";
                    jTextField5.setText(null);
                    flag=true;
                    break;
                }
            }
        }
        return errorLabel;
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
