package StudentPart;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ActiveBorrowedBooks extends javax.swing.JFrame {
    String studentId;
    /**
     * Creates new form NewJFrame3
     * @param StudentId
     */
    public ActiveBorrowedBooks(String Id) {
        initComponents();
        getContentPane().setBackground(Color.BLUE);
        this.studentId=Id;
        setVisible(true);
        jTable1.setVisible(true);
        Connection con=null;
        PreparedStatement pst=null;
        try
        {
            int count=0;
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            String url = "jdbc:mysql://localhost:3306/library";
            String MySQLname = "root";
            String dbPassword = "";
            //Class.forName("com.mysql.jdbc.Driver");
            con=(Connection) DriverManager.getConnection(url,MySQLname,dbPassword);
//            pst=(PreparedStatement)con.prepareStatement("select issuedbooks.BookISBNNo, book.BookName, issuedbooks.IssueId, issuedBooks.DueTimeStamp from issuedBooks, book " +
//                                                    "WHERE book.ISBNNo = issuedBooks.BookISBNNo and issuedBooks.StudentId= ? " +
//                                                    "and   IssueId NOT IN (select returnbooks.IssueId from returnBooks " +
//                                                    "where issuebooks.StudentId = ? and returnbooks.IssueId = issuedbooks.IssueId)");
            pst=(PreparedStatement)con.prepareStatement("SELECT issuedbooks.BookISBNNo, book.BookName, issuedbooks.IssueId, issuedbooks.DueTimeStamp FROM issuedBooks,book WHERE book.ISBNNo = issuedBooks.BookISBNNo AND issuedBooks.StudentId = ? AND IssueId IN ( SELECT returnBooks.IssueId from returnbooks, issuedbooks WHERE issuedbooks.StudentId = ? AND returnBooks.IssueId = issuedBooks.IssueId)");
            //xyz=jTextField1.getText();
            pst.setString(1,studentId);
            pst.setString(2,studentId);
            jTextField1.setText(studentId);
            ResultSet rs=(ResultSet) pst.executeQuery();
            while(rs.next())
            {
                count++;
                String BookISBNNO = rs.getString("BookISBNNo");
                String BookName=rs.getString("BookName");
                String IssuedDate=rs.getString("IssueId");
                String DueDate=rs.getString("DueTimeStamp");
                System.out.println("BookISBNNo "+BookISBNNO);
                System.out.println("BookName: "+BookName);
                System.out.println("IssuedDate: "+IssuedDate);
                System.out.println("DueDate: "+DueDate);
                model.addRow(new Object[]{BookISBNNO,BookName,IssuedDate,DueDate});
            }
            con.close();
            pst.close();
            rs.close();
            if(count==0)
            {
                JOptionPane.showMessageDialog(this, "No Active-Borrowed Books");
            }
        }catch (Exception e1) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, e1);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ISBN N0", "Book Name", "Issue TimeStamp", "Due TimeStamp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 170, 550, 360));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 105, 160, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel1.setText("Student Id:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Active Borrowed Books");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/0_PreviousButton.jpg"))); // NOI18N
        jButton2.setToolTipText("To Go To Previous Page.");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        //
        //
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new StudentPart(studentId);
        //new StudentPart(studentId).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
